[package]
name = "antilysis"
version = "0.1.1"
edition = "2021"
description = "Anti-analysis and anti-vm for windows"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.29.0"
